{{- if .Values.cronJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "trip-processor.fullname" . }}-load-dd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "trip-processor.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.schedule | quote}}
  concurrencyPolicy: "Forbid"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
          {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
          labels:
            {{- include "trip-processor.selectorLabels" . | nindent 12 }}
        spec:
          containers: []
          restartPolicy: OnFailure
{{ end }}          
