apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "trip-processor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data: []
